### PR TITLE
Centralize env config setup

### LINKED ISSUE #780: [Refactor]: Centralize environment variables into a typed Config singleton
### What would you like?

A typed singleton `Config` class that centralizes all ~60 environment variables. Instead of scattered `process.env.X` calls with inconsistent parsing and fallback logic, all env access goes through one object loaded once at startup.

### Why is this needed?

- **No startup validation** — missing required vars (e.g. `STRIPE_PRIVATE_KEY`) only crash when that code path is first hit at runtime, not at boot.
- **Inconsistent parsing** — some vars use `parseInt()` with NaN fallbacks, others use `Number()`, others use `||` vs `??`. Boolean checks mix `=== 'true'` patterns.
- **Duplicated defaults** — fallback values like `BCRYPT_ROUNDS = 12` or `REDIS_PORT = 6379` are hardcoded inline wherever they're used.
- **Hard to discover** — no single place to see what env vars the app needs. You have to grep across 40+ source files.

### How could it be implemented?

A `src/config.ts` singleton with typed properties, loaded once via `dotenv` + parsing:

```typescript
class Config {
  private static instance: Config;

  // Groups
  readonly database: { connection: string; host: string; port: number; ... };
  readonly redis: { host: string; port: number; connectTimeoutMs: number };
  readonly stripe: { privateKey?: string; publicKey?: string; ... };
  readonly smtp: { host?: string; port?: number; ... };
  // ...

  private constructor() { /* parse + validate all process.env once */ }

  static get(): Config {
    if (!this.instance) this.instance = new Config();
    return this.instance;
  }

  // For test isolation
  static reset(): void { this.instance = undefined; }
}
```

**Refactor scope:** Medium — mechanically replace `process.env.X` across ~40-50 files. No database or API changes. Low risk since it's the same values, just centralized.

**Test impact:** `test/setup.ts` already sets env vars before anything runs, so the singleton would pick them up on first access. A `Config.reset()` method handles test isolation.

### Other information

Current inventory: ~60 unique env vars, ~24 with hardcoded defaults, 2 explicitly required (`NAME`, `JWT_KEY_PATH`), ~15 conditionally required (LDAP, Stripe, SMTP, GEWIS groups).

### PR DESCRIPTION
**Pull request by JustSamuel**
# Description
Move everything env related to a single source of truth with sensible defaults.

## Related issues/external references
Closes #780

## Types of changes
- Refactor

### CODE REVIEW

File: src/helpers/pagination.ts [hunk 1]
```diff
@@ -25,14 +25,15 @@
  */
 
 import { Request } from 'express';
+import Config from '../config';
 
-export const PAGINATION_DEFAULT = 25;
+export const PAGINATION_DEFAULT = 20;
```
Comment (RubenLWF) [inline src/helpers/pagination.ts]: question:

why this change?

File: src/config.ts [hunk 2]
```diff
@@ -0,0 +1,368 @@
...
+  return Number.isNaN(parsed) ? fallback : parsed;
+}
+
+function getBoolean(name: string, fallback: boolean = false): boolean {
+  const rawValue = getOptionalString(name);
+  if (rawValue == null) return fallback;
+
+  return rawValue === 'true';
+}
+
```
Comment (RubenLWF) [inline src/config.ts:57]: suggestion:

remove this double empty line since we do not do this anywhere else

File: src/config.ts [hunk 3]
```diff
@@ -0,0 +1,368 @@
...
+function getOptionalString(name: string): string | undefined {
+  const value = process.env[name];
+  if (value == null) return undefined;
+
+  const trimmed = value.trim();
+  // Node.js stringifies `process.env.X = undefined` as "undefined"
+  return (trimmed === '' || trimmed === 'undefined') ? undefined : trimmed;
+}
+
+
```
Comment (RubenLWF) [inline src/config.ts]: suggestion:

remove this double empty line since we do not do this anywhere else

**Review by RubenLWF — CHANGES_REQUESTED** [review]

File: src/helpers/pagination.ts (hunk 1 above)
Comment (JustSamuel) [reply src/helpers/pagination.ts]: The constant was accidentally changed to 20 to match the hardcoded fallback in `Config` — but that was the wrong direction. Reverted `PAGINATION_DEFAULT` back to 25 and updated the fallback in `config.ts` to 25 as well so they're consistent.
